import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { catalogHash, emit } from '@ts-pf/codegen'
import { procedure, router } from '@ts-pf/contract'
import { catalog, type ProcedureCatalog } from '@ts-pf/docs'
import { stream } from '@ts-pf/stream'
import { describe, expect, it } from 'vitest'
import { z } from 'zod'
import { planetCatalog } from './planet-catalog.js'

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/planet.d.ts',
)

describe('emit', () => {
  it('prints nested planet.find / list / chat', () => {
    const dts = emit(planetCatalog())
    expect(dts).toContain('export type Contract = {')
    expect(dts).toContain('planet: {')
    expect(dts).toContain('find: ContractProcedure<')
    expect(dts).toContain('{ id: number }')
    expect(dts).toContain('{ id: number; name: string }')
    expect(dts).toContain(
      'list: ContractProcedure<void, { id: number; name: string }[]>',
    )
    expect(dts).toContain(
      'chat: ContractProcedure<{ prompt: string }, AsyncIterable<{ token: string }>>',
    )
  })

  it('wraps declared error data in Phantom and omits protocol errors', () => {
    const dts = emit(planetCatalog())
    expect(dts).toContain('NOT_FOUND: {')
    expect(dts).toContain('status: 404')
    expect(dts).toContain('data: Phantom<{ id: number }>')
    expect(dts).not.toContain('VALIDATION')
    expect(dts).not.toContain('BAD_REQUEST')
    expect(dts).not.toContain('METHOD_NOT_ALLOWED')
    expect(dts).not.toContain('PAYLOAD_TOO_LARGE')
    expect(dts).not.toMatch(/\bINTERNAL\b/)
  })

  it('omits data on errors without a schema', () => {
    const spec = catalog(
      router({
        planet: {
          ping: procedure.errors({ GONE: { status: 410, message: 'gone' } }),
        },
      }),
    )
    const dts = emit(spec)
    expect(dts).toContain('GONE: {')
    expect(dts).toContain('status: 410')
    expect(dts).toContain("message: 'gone'")
    expect(dts).not.toContain('data:')
  })

  it('prints stream input and stream output', () => {
    const spec = catalog(
      router({
        chat: procedure
          .input(stream(z.object({ chunk: z.number() })))
          .output(stream(z.object({ token: z.string() }))),
      }),
    )
    const dts = emit(spec)
    expect(dts).toContain(
      'chat: ContractProcedure<AsyncIterable<{ chunk: number }>, AsyncIterable<{ token: string }>>',
    )
  })

  it('prints unavailable as unknown and throws when failOnUnavailable', () => {
    const spec = catalog(
      router({
        ping: procedure.output({ not: 'a schema' }),
      }),
    )
    expect(emit(spec)).toContain('ping: ContractProcedure<void, unknown>')
    expect(() => emit(spec, { failOnUnavailable: true })).toThrow(
      /Unavailable schema at ping output/,
    )
  })

  it('throws on an empty path', () => {
    const spec: ProcedureCatalog = {
      ...planetCatalog(),
      procedures: [
        {
          path: [],
          key: '',
          meta: {},
          errors: [],
        },
      ],
    }
    expect(() => emit(spec)).toThrow(/Empty procedure path/)
  })

  it('includes catalogVersion and matching catalogHash in the banner', () => {
    const spec = planetCatalog()
    const dts = emit(spec)
    expect(dts).toContain(' * catalogVersion: 1')
    expect(dts).toContain(` * catalogHash: ${catalogHash(spec)}`)
    expect(emit(spec, { banner: false })).not.toContain(
      'Generated by @ts-pf/codegen',
    )
  })

  it('round-trips JSON.parse(JSON.stringify(catalog))', () => {
    const spec = planetCatalog()
    const copy = JSON.parse(JSON.stringify(spec)) as ProcedureCatalog
    expect(emit(copy)).toBe(emit(spec))
  })

  it('is deterministic', () => {
    const spec = planetCatalog()
    expect(emit(spec)).toBe(emit(spec))
  })

  it('matches the checked-in planet fixture', () => {
    const fixture = readFileSync(fixturePath, 'utf8')
    expect(emit(planetCatalog())).toBe(fixture)
  })

  it('throws on unsupported catalogVersion', () => {
    const spec = {
      ...planetCatalog(),
      catalogVersion: 2,
    } as unknown as ProcedureCatalog
    expect(() => emit(spec)).toThrow(/Unsupported catalogVersion/)
  })
})
