import type {
  CatalogError,
  CatalogProcedure,
  CatalogSchema,
  ProcedureCatalog,
} from '@ts-pf/docs'
import { catalogHash } from './hash.js'
import { aliasName, pascalCase, quoteKey, quoteString } from './names.js'
import { PHANTOM_SOURCE } from './phantom.js'
import { printJsonSchema } from './print-type.js'
import { buildTree, type TreeNode } from './tree.js'

export type EmitOptions = {
  /** Type name. Default `Contract`. */
  name?: string
  /** Throw if any input/output/error data is `unavailable`. Default false. */
  failOnUnavailable?: boolean
  /** Default true. Header comment with catalogVersion + catalogHash. */
  banner?: boolean
}

export function emit(
  catalog: ProcedureCatalog,
  options: EmitOptions = {},
): string {
  if (catalog.catalogVersion !== 1) {
    throw new Error(
      `Unsupported catalogVersion: ${String(catalog.catalogVersion)}`,
    )
  }
  if (!Array.isArray(catalog.procedures)) {
    throw new Error('catalog.procedures must be an array')
  }

  const name = options.name ?? 'Contract'
  const failOnUnavailable = options.failOnUnavailable ?? false
  const banner = options.banner ?? true
  const aliases: Array<{ name: string; ts: string }> = []
  const tree = buildTree(catalog.procedures)
  const body = printNamespace(tree, aliases, failOnUnavailable)

  const lines: string[] = []
  if (banner) {
    lines.push('/**')
    lines.push(' * Generated by @ts-pf/codegen. Do not edit.')
    lines.push(` * catalogVersion: ${String(catalog.catalogVersion)}`)
    lines.push(` * catalogHash: ${catalogHash(catalog)}`)
    lines.push(' */')
    lines.push('')
  }
  lines.push("import type { ContractProcedure } from '@ts-pf/contract'")
  lines.push('')
  lines.push(PHANTOM_SOURCE)
  lines.push('')
  for (const alias of aliases) {
    lines.push(`type ${alias.name} = ${alias.ts}`)
    lines.push('')
  }
  lines.push(`export type ${name} = ${body}`)
  lines.push('')
  return lines.join('\n')
}

function printNamespace(
  tree: Map<string, TreeNode>,
  aliases: Array<{ name: string; ts: string }>,
  failOnUnavailable: boolean,
): string {
  const lines = ['{']
  for (const [key, node] of tree) {
    const value =
      node.kind === 'proc'
        ? printProcedure(node.proc, aliases, failOnUnavailable)
        : printNamespace(node.children, aliases, failOnUnavailable)
    const valueLines = value.split('\n')
    lines.push(`  ${quoteKey(key)}: ${valueLines[0]}`)
    for (const line of valueLines.slice(1)) {
      lines.push(`  ${line}`)
    }
  }
  lines.push('}')
  return lines.join('\n')
}

function printProcedure(
  proc: CatalogProcedure,
  aliases: Array<{ name: string; ts: string }>,
  failOnUnavailable: boolean,
): string {
  const input = printSlot(proc.input, {
    path: proc.path,
    suffix: 'Input',
    missing: 'void',
    slot: 'input',
    aliases,
    failOnUnavailable,
  })
  const output = printSlot(proc.output, {
    path: proc.path,
    suffix: 'Output',
    missing: 'unknown',
    slot: 'output',
    aliases,
    failOnUnavailable,
  })
  const errors = printErrorMap(
    proc.errors,
    proc.path,
    aliases,
    failOnUnavailable,
  )
  const args = errors === undefined ? [input, output] : [input, output, errors]
  const compact = args.every((arg) => !arg.includes('\n'))
  if (compact) {
    return `ContractProcedure<${args.join(', ')}>`
  }
  return `ContractProcedure<\n${args.map((arg) => indentLines(arg, 1)).join(',\n')}\n>`
}

function printErrorMap(
  errors: readonly CatalogError[],
  path: readonly string[],
  aliases: Array<{ name: string; ts: string }>,
  failOnUnavailable: boolean,
): string | undefined {
  if (errors.length === 0) {
    return undefined
  }
  const fields: string[] = []
  for (const err of errors) {
    const body: string[] = []
    if (err.status !== undefined) {
      body.push(`status: ${String(err.status)}`)
    }
    if (err.message !== undefined) {
      body.push(`message: ${quoteString(err.message)}`)
    }
    if (err.data !== undefined) {
      const data = printSlot(err.data, {
        path,
        suffix: `Error${pascalCase(err.code)}`,
        missing: 'unknown',
        slot: `error ${err.code} data`,
        aliases,
        failOnUnavailable,
      })
      body.push(`data: Phantom<${data}>`)
    }
    const def =
      body.length === 0
        ? '{}'
        : `{\n${body.map((line) => `  ${line}`).join('\n')}\n}`
    const defLines = def.split('\n')
    fields.push(`${quoteKey(err.code)}: ${defLines[0]}`)
    for (const line of defLines.slice(1)) {
      fields.push(line)
    }
  }
  return `{\n${fields.map((line) => `  ${line}`).join('\n')}\n}`
}

function printSlot(
  schema: CatalogSchema | undefined,
  opts: {
    path: readonly string[]
    suffix: string
    missing: string
    slot: string
    aliases: Array<{ name: string; ts: string }>
    failOnUnavailable: boolean
  },
): string {
  if (schema === undefined) {
    return opts.missing
  }
  if (schema.kind === 'unavailable') {
    if (opts.failOnUnavailable) {
      throw new Error(
        `Unavailable schema at ${opts.path.join('/')} ${opts.slot}: ${schema.reason}`,
      )
    }
    return 'unknown'
  }
  if (schema.kind === 'stream') {
    const item = printSlot(schema.item, {
      ...opts,
      suffix: `${opts.suffix}Item`,
      missing: 'unknown',
      slot: `${opts.slot} item`,
    })
    return `AsyncIterable<${item}>`
  }
  const printed = printJsonSchema(schema.jsonSchema, {
    prefix: aliasName(opts.path, opts.suffix),
  })
  opts.aliases.push(...printed.aliases)
  return printed.ts
}

function indentLines(text: string, n: number): string {
  const pad = '  '.repeat(n)
  return text
    .split('\n')
    .map((line) => `${pad}${line}`)
    .join('\n')
}
