/**
 * Generated by @ts-pf/codegen. Do not edit.
 * catalogVersion: 1
 * catalogHash: sha256:273e680fb149ea7b9915e6deaebafb0f42a19992175d54a9db5ea7bf2d7dc270
 */

import type { ContractProcedure } from '@ts-pf/contract'

type Phantom<T> = {
  readonly '~standard': {
    readonly version: 1
    readonly vendor: 'ts-pf-codegen'
    readonly types: { readonly input: T; readonly output: T }
    readonly validate: (value: unknown) => { readonly value: T }
  }
}

export type Contract = {
  planet: {
    /**
     * List known planets
     */
    list: ContractProcedure<void, { id: number; name: string }[]>
    /**
     * Find a planet by id
     */
    find: ContractProcedure<
      { id: number },
      { id: number; name: string },
      {
        NOT_FOUND: {
          status: 404
          data: Phantom<{ id: number }>
        }
      }
    >
    /**
     * Create a planet
     */
    create: ContractProcedure<{ name: string }, { id: number; name: string }>
  }
}
